Cleaned up aTHX_ useage and some minor warnings.
Failing to compile with the following errors:

XS.xs: In function ‘build_trace’:
XS.xs:229: error: ‘const struct block_sub’ has no member named ‘hasargs’
XS.xs: In function ‘frame_to_caller’:
XS.xs:343: error: ‘struct <anonymous>’ has no member named ‘blku_u16’
make: *** [XS.o] Error 1

These can both be trace backed to build_trace function.

1) XS.xs:229 > f->blk_sub.hasargs = cx->blk_sub.hasargs // This indicates the correct struct is not being used

2) XS.xs:343 > if (CxOLD_OP_TYPE(cx) == OP_ENTEREVAL) {

The macro CxOLD_OP_TYPE is expecting a cx->blk_u16  (from perl code in 5.12.0)
cop.h+404 : #define CxOLD_OP_TYPE(cx)       (((cx)->blk_u16) >> 7)

IMO I think your union here XS.xs :42 is a bit fuzzy.

Hope this helps! :)